language: python
services: docker

env:
  global:
    - ROLE_NAME: pgsql_replication
  matrix:
    - MOLECULE_DISTRIBUTION: centos7
    - MOLECULE_DISTRIBUTION: centos8

install:
  - pip install molecule[lint] docker

before_script:
  # Remove "ansible-role-" prefix from role name
  - cd ../
  - mv ansible-role-${ROLE_NAME/_/-} $ROLE_NAME
  - cd $ROLE_NAME

script:
  # Run tests
  - molecule test --all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
