- name: Configure master server
  lineinfile:
    state: present
    backrefs: yes
    dest: "{{ pgsqlrep_data_path[pgsql_major_version] }}/postgresql.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop: "{{ pgsqlrep_postgres_conf_lines }}"
  notify: restart postgresql

- name: Create replication user account
  postgresql_user:
    name: "{{ pgsqlrep_user }}"
    password: "{{ pgsqlrep_password }}"
    role_attr_flags: replication
  become: yes
  become_user: postgres

- name: Add trust in pg_hba.conf
  lineinfile:
    state: present
    dest: "{{ pgsqlrep_data_path[pgsql_major_version] }}/pg_hba.conf"
    regexp: 'host.*replication.*{{ item }}/32.*trust'
    line: 'host    replication    {{ pgsqlrep_user }}  {{ item }}/32 trust'
  loop: "{{ pgsqlrep_replica_address }}"
  notify: restart postgresql
